### ISSUE TITLE
Wrong error message for non-existing account

### ISSUE THREAD

**Issue by tdviet** [indigo-dc/liboidc-agent-py#6]
When using the code given in the documentation:

try:
    print(agent.get_access_token(account_name))
except agent.OidcAgentError as e:
    print("ERROR oidc-agent: {}".format(e))

If the account does not exist, the error message is:

ERROR oidc-agent: OIDC_REMOTE_SOCK env var not set

**Comment by zachmann** [comment]
You're right this error message seems wrong to users and is confusing. It is not directly related to the python lib. We will address this issue with the next oidc-agent release 4.1.0
