### ISSUE TITLE
License file missing in tar.gz from PyPi

### ISSUE THREAD

**Issue by enolfc** [indigo-dc/liboidc-agent-py#8]
I'm trying to build a conda package for this one relying on [grayskull](https://github.com/conda-incubator/grayskull), which generates an almost working `meta.yml` for the package. However it fails to build with an error like:

```
ValueError: License file given in about/license_file (/home/jovyan/liboidcagent/LICENSE) does not exist in source root dir or in recipe root dir (with meta.yaml)
```

Which apparently is because the LICENSE file is not available in the [tar.gz obtained from PyPi](https://files.pythonhosted.org/packages/40/01/c288118d71d81a2f8716b559538c90dc310ada447b20b5588c1a957c80f5/liboidcagent-0.3.2.tar.gz)

Could the LICENSE file be added to the generated tar? Alternatively a package in conda-forge would also make things easy :)

**Comment by enolfc** [comment]
Using this: https://gitter.im/conda-forge/conda-forge.github.io?at=5cdb037c6fd7c11cd8b96586 as workaround for now

**Comment by zachmann** [comment]
Thanks for the info.
I updated the build, so the license file is now included in the tarball.
The [version 0.3.3 on PyPi](https://files.pythonhosted.org/packages/ef/be/406fea6ef0cecdb8f1580648c9a6146aeac94ed8a46d6aa7d2417de92611/liboidcagent-0.3.3.tar.gz) has it included.
